import { SPORT_LEVEL_LIST_TYPE } from './type';

export const NAV_TITLE_NAME = {
  all: t('全部盘口'),
  final: t('全局'),
  r1: t('第一局'),
  r2: t('第二局'),
  r3: t('第三局'),
  r4: t('第四局'),
  r5: t('第五局'),
  r6: t('第六局'),
  r7: t('第七局'),
  r8: t('第八局'),
  r0: t('第九局'),
  r10: t('第十局'),
  map1: t('地图一'),
  map2: t('地图二'),
  map3: t('地图三'),
  map4: t('地图四'),
  map5: t('地图五'),
  map6: t('地图六'),
  map7: t('地图七'),
  map8: t('地图八'),
  map9: t('地图九'),
  map10: t('地图十'),
  q1: t('第一节'),
  q2: t('第二节'),
  q3: t('第三节'),
  q4: t('第四节'),
  q6: t('第六节'),
  q7: t('第七节'),
  q8: t('第八节'),
  q9: t('第九节'),
  q10: t('第十节')
};

export const SPORT_LEVEL_LIST = [
  { currentPage: 1, pageSize: 100, key: 'all', list: [] },
  { currentPage: 1, pageSize: 100, key: 'final', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r1', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r2', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r3', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r4', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r6', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r7', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r8', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r9', list: [] },
  { currentPage: 1, pageSize: 100, key: 'r10', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map1', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map2', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map3', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map4', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map4', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map5', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map6', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map7', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map8', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map9', list: [] },
  { currentPage: 1, pageSize: 100, key: 'map10', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q1', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q2', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q3', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q4', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q5', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q6', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q7', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q8', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q9', list: [] },
  { currentPage: 1, pageSize: 100, key: 'q10', list: [] }
];
